### ISSUE TITLE
Hosting metadata

### ISSUE THREAD

**Issue by martinthomson** [reschke/oobencoding#11]
The draft is complicated significantly by virtue of constructing metadata from three sources:
1. The original message/response
2. The metadata in the body of the original response
3. The protected payload of the secondary resource

(I think that I've gotten the order right here, but I'm not 100%)

If this is truly a content-encoding, then we can retain that property and simplify things greatly.  Then the processing rules don't need to concern themselves with header fields at all.

What is the use case for including header fields in the secondary resource?

**Comment by reschke** [comment]
I agree that it's confusing, but I'm not quit sure which metadata your question is about :-)

Is this about 3) "the protected payload of the secondary resource"? The examples in Section 3.4 use it; 3.4.1 for Content-Language, 3.4.2 for  encryption information.

Let's focus on 3.4.2 for now? Are you saying this is wrong/bad?

If we don't need the metadata in the protected payload then we wouldn't need the application/http media type, right?

**Comment by martinthomson** [comment]
3.4.2 is a less informative example, but sure.  The `Crypto-Key` header field, by virtue of its construction, could appear in the header fields of either response and still be effective.  Thus, the key could be in the primary resource without any loss of comprehension.

On the basis of 3.4.2 and `Crypto-Key`, we don't have any justification for metadata in the JSON, nor does it motivate the use of `message/http` for the payload.

(`Crypto-Key` could also be added to the outer header fields of the secondary resource.  That would make it available, but it would lead to a complete lack of confidentiality.  And I don't think that we want to be even looking at those header fields when it comes to constructing the final response.)

**Comment by reschke** [comment]
Crypto-Key is defined in https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-00#section-4 as:

   _An Crypto-Key header field can be used to describe the input keying
   material used in the Encryption header field._
   _..._
   _The value or values provided in the Crypto-Key header field is valid
   only for the current HTTP message unless additional information
   indicates a greater scope._

So I think to make it apply to the secondary resource, some additional text is needed over there.

**Comment by reschke** [comment]
@martinthomson can you do a sanity-check, in particular on the example using the encryption encoding?

**Comment by gaperik** [comment]
@julian. This describes OOB without a resource map. How is this
extended/changed in case the origin server provides a resource map, e.g.
using a LINK header? Guess we can describe that elsewhere, e.g. resource
map draft?

2016-02-08 15:26 GMT+01:00 Julian Reschke notifications@github.com:

**Comment by reschke** [comment]
Yep, that's an orthogonal issue. The resource map either would need to be embedded into the JSON payload, or referenced using a Link header field.

**Comment by gaperik** [comment]
Check.

**Comment by reschke** [comment]
message encapsulation was removed in draft 03
