### ISSUE TITLE
HTTP OPTIONS

### ISSUE THREAD

**Issue by Kevsy** [reschke/oobencoding#2]
May be worth mentioning why HTTP OPTIONS is not appropriate or ideal for the initial request, e.g. because it can't be cached, no browser support, etc.

**Comment by reschke** [comment]
Not sure I understand; why would you do an OPTIONS anyway?

**Comment by Kevsy** [comment]
My mistake, sorry! Would only apply if the client wanted to query the possibility of a cached version first, which is of course not the case here.
