### ISSUE TITLE
LINK header instead of URI object

### ISSUE THREAD

**Issue by Kevsy** [reschke/oobencoding#3]
How about a Link header instead of the JSON object for the URI? e.g. per the 3.3.1 Basic Example:

Request:
 GET /test HTTP/1.1
     Host: www.example.com
     Accept-Encoding: gzip, out-of-band

  Response:

```
 HTTP/1.1 200 OK
 Date: Thu, 14 May 2015 18:52:00 GMT
 Content-Type: text/plain
 Cache-Control: max-age=10, public
 Content-Encoding: out-of-band
 Link: <http://example.net/bae27c36-fa6a-11e4-ae5d-00059a3c7a00>; rel="payload"
```

1- as per RFC5988 this would require registration of a new relation type ("payload" for example)
2- if metadata is needed this can be included in the body, as described currently.
3- GET is still the appropriate method, because HEAD would not return any body metadata

**Comment by reschke** [comment]
I'd like to have all information needed to undo the content coding in-band...
