### ISSUE TITLE
Move Encryption-Key to header fields

### ISSUE THREAD

**Issue by martinthomson** [reschke/oobencoding#4]
The Encryption-Key header field doesn't need to be in the response body.  It's only used to prime a dictionary of keys, so having it apply to the request isn't strictly necessary.  (It does raise the question about what scope the key identifiers need to be resolved in, but that's a problem for my draft, I suppose.)

That might allow you to remove metadata from the payload entirely.

**Comment by salvatoreloreto** [comment]
if it doesn't need to be in the body, and I tend to agree, I am wondering if we really need a body 
or at least define explicitly in the draft what the body should or should not carry.
yes in that case we should remove entirely metadata from the payload

Martin if I read your comment correctly you are saying that one reason of having it in the body would be that the key is applicable only to the specific request. Is that correct?

**Comment by reschke** [comment]
I have a big problem when we define a content coding, and the actual information needed to retrieve the content is not in the payload.

**Comment by salvatoreloreto** [comment]
well the Encryption-Key is of course one important and needed piece of information to retrieve the content but not the only one.
The body could include other information on how to retrieve the actual information, and also how to retrieve other resources hosted by the same server or related to the resource that has been initially requested.
Having said that, I think the main questions to be discussed here are
1) the scope of the key identifier ... and the difference if they are difference if it is transported as payload or as header
2) can the same metadata received by the initial request origin be used in all the subsequent requests to the Cache
3) (not how to prime a dictionary of keys) but how to use the key in the dictionary... even if I am not sure it should be discussed in this draft, but for sure knowing it would help

**Comment by martinthomson** [comment]
I took Julian's view until it I realized that this "just works" with the current composition.  You don't need the key ID to compose the response.  Rather, you just need rules about how to compose header fields, and in particular, how content-encodings are processed.  Content-encodings would have to be applied as follows:

Each `oob` content encoding is parsed (using JSON) and retrieved (or fetched).  The content-encodings that are declared by the out-of-band resource are applied to that before any further content-encodings declared by the origin are applied.  That process can be recursive.

So if you could have the following setup:

A reports oob (B), gzip
B reports oob(C)
C reports aes-gcm-128

That composes perfectly well.

@salvatoreloreto 

>  1) the scope of the key identifier ... and the difference if they are difference if it is transported as payload or as header

I don't think this is as big a problem as I originally thought for this scenario.  If you compose header fields as you go, then the header field and body are in the same place at the same time.  There is a general problem that I need to address for the header field, but this isn't made worse by using oob encoding.

>  2) can the same metadata received by the initial request origin be used in all the subsequent requests to the Cache

I think that all we need to do is apply the caching rules as they are.  If you are caching the composed response, then you can use the composed response.  However, the oob content might expire before the response from the origin, in which case, the cache can be consulted again.

>  3) (not how to prime a dictionary of keys) but how to use the key in the dictionary... even if I am not sure it should be discussed in this draft, but for sure knowing it would help 

I'm not sure that I follow the problem here, can you explain more?

**Comment by salvatoreloreto** [comment]
@martinthomson 
above you wrote
_The Encryption-Key header field doesn't need to be in the response body. It's only used to prime a dictionary of keys, so having it apply to the request isn't strictly necessary. (It does raise the question about what scope the key identifiers need to be resolved in, but that's a problem for my draft, I suppose.)_

It is not clear to me how the Encryption-Key header provided from the origin server is used.
Above you say it is only used to prime a dictionary of keys!
I thought the Encryption-Key provided from the origin server is the one it will used to decrypt the body of the subsequent request to the cache box, but you it seems that that is not necessarily the case and the client can use a different key present in its key dictionary.
Can you clarify how you envision the mechanism?

**Comment by martinthomson** [comment]
Encryption-Key establishes a map of keyid to keys.  Encryption references those keys.  Thus, you can have this:

```
HTTP/1.1 200 OK
Content-Encoding: oob
Encryption-Key: keyid=x;key=k

[{ "URI": "https://other/..." }]
```

Composed with:

```
HTTP/1.1 200 OK
Encryption: salt=s;keyid=x

...
```

And it becomes something like from the examples in the encryption draft.  Simple.

**Comment by reschke** [comment]
metadata was removed in draft 06
