### ISSUE TITLE
need to discuss impact on Vary and ETags

### ISSUE THREAD

**Issue by reschke** [reschke/oobencoding#6]

**Comment by gaperik** [comment]
yep. eTag will be used both on the client-cache and origin-cache interfaces. The Vary is another topic. Perhaps we should spit this issue into one for eTag and one for Vary at some point?

**Comment by reschke** [comment]
I added a mention of Vary. Not sure what to say about etags except "be careful" (remember the mod_deflate breakage). Maybe indeed open a separate ticket.

**Comment by gaperik** [comment]
Easier to discuss etag for oob when we have some clear use cases for it.
Better to open a new ticket when there is a clear problem/solution to
discuss.

2015-09-08 13:06 GMT+02:00 Julian Reschke notifications@github.com:
