### ISSUE TITLE
Secondary resource representation not available

### ISSUE THREAD

**Issue by gaperik** [reschke/oobencoding#7]
The current draft states "retry the request to the origin server without including
   "out-of-band" in the Accept-Encoding request header field". What if the resource was not available because of the origin server deliberately having removed it using a separate procedure? In that case, the origin server may want to have the client use another secondary server?

**Comment by gaperik** [comment]
A few thoughts about some possible guidelines for a solution we can discuss:
1) There may be different reasons for the oob delivery to fail; secondary server not reachable, object not found, a content integrity check failing. This may be relevant information for an origin server in deciding whether to use a oob secondary server or not.
2) The risk of a loop is there. Hence, it may be appropriate for the client to indicate that it does not accept OOB henceforth. It may depend on the actual error case.
3) The origin server may have referred delivery of other resource to the secondary server than the one that the client failed to retrieve. What should be done about these? One solution may be to enable to origin server to provide a directive to the client to stop usage the oob secondary server for any resource.

**Comment by reschke** [comment]
I'll try an approach in which we piggy-back this information to the GET request, using Link header fields.

Such as:

```
Link: <http://cache/resource>, rel=serverdown
```

with relation types for the common use cases we find.

**Comment by gaperik** [comment]
Quite straight forward and a got starting point. More complex approaches like the report URI in CSP seem not applicable yet. Agree this is the first thing to try out.
